Landing page
WildCodeSchool/reims-202109-php-project3-motorbox pull request #10
Opened 2021-12-09 10:27 UTC by JmJames51

2021-12-09 10:29 UTC, MarjorieThomassin commented
conflicts to resolve

2021-12-09 14:08 UTC, rocambille requested changes

2021-12-09 14:08 UTC, rocambille commented on assets/styles/app.scss
> +    height: 10vh;
buttons should not have a fixed size: use layout or spacing if you need it to take more space

2021-12-09 14:08 UTC, rocambille commented on templates/home/landingpage.html.twig
> +			</div>
the div looks useless here... and your buttons will end up as links, so prefer <a> tags

2021-12-10 09:50 UTC, MarjorieThomassin commented
conflicts to resolve

2021-12-10 12:48 UTC, closed without merging