Updatepartentity
WildCodeSchool/reims-202109-php-project3-motorbox pull request #58
Opened 2022-01-18 14:32 UTC by nibor51

2022-01-18 15:31 UTC, rocambille requested changes

2022-01-18 15:31 UTC, rocambille commented on src/Entity/Part.php
> +use phpDocumentor\Reflection\Types\Integer;
is this really used?

2022-01-18 15:31 UTC, rocambille commented on templates/vehicle/parts.html.twig
> +                <progress class="progress-part" value = "{{ vehicle.usedHour - part.PartUseTime }}" max = "{{ part.lifespan }}"> </progress>
partUseTime, not PartUseTIme

2022-01-18 15:33 UTC, nibor51 commented on src/Entity/Part.php
> +use phpDocumentor\Reflection\Types\Integer;
nom i fix it

2022-01-23 06:08 UTC, nibor51 reviewed
I fixed what you told me

2022-01-25 08:23 UTC, merged