Form css
WildCodeSchool/reims-202109-php-project3-motorbox pull request #59
Opened 2022-01-18 15:39 UTC by SousaLuis

2022-01-18 15:55 UTC, rocambille requested changes

2022-01-18 15:55 UTC, rocambille commented on templates/user/login.html.twig
> +            </div>
this end tag closes opening tag in line 12, while the form is still opened. your opening/closing tags don't match

2022-01-25 08:30 UTC, JmJames51 commented on templates/user/login.html.twig
> +            </div>
fixed

2022-01-25 08:35 UTC, rocambille commented on templates/user/login.html.twig
> +            </div>
count opening/closing div tags

2022-01-25 08:45 UTC, JmJames51 commented on templates/user/login.html.twig
> +            </div>
yep, i've missed a end tag, should be fix now

2022-01-25 09:06 UTC, merged